name: auth_prime
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  font_awesome_flutter: ^9.2.0
  rename: ^2.0.1

  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.7
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  shared_preferences: ^2.0.13
  google_fonts: ^2.3.1
  fluttertoast: ^8.0.9
  firebase_storage: ^10.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
